### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EsioFreitas** [UnBArqDsw/2020.1_G10_QRodizio#15]
**Visão geral**
Da para ver que a ideia está bem definida. Parabéns. Os documentos estão com histórico de revisẽs e isso é bem legal. No entanto nem todos os documentos estão referência. Cuidado com essa falta de padronização. Além disso, ainda falta documentos de elicitação. Cuidado para não ficarem atrasados. Por fim, só há documentos do Cauê e Fábio. Os outros membros não trabalharam? 

**5w2h** 
Muito legal! Mostra o alinhamento da ideia do grupo. No entanto falta a versão do grupo que está vazia.

**RP** 
Os rp estão fracos, pois estão parecendo mapas mentais. Faltam mostrar os fluxos e trocam entre eles. Além disso, vcs podem melhorar as artes.

**Ishikawa** 
Muito bons! Parabens

**Comment by Caiocbeleza** [comment]
Acabei de subir os artefatos que eu fiz la na branch "base", se vc puder dar uma olhada lá e dar um feedback neles depois... Valeu :D

**Comment by EsioFreitas** [comment]
@Caiocbeleza , muito bom os documentos. No entanto o RP sofre da mesma observação acima. Não esqueça de registrar o versionamento dos documentos. :D

**Comment by lucasmidlhey** [comment]
Os documentos estavam na fila de espera ate o gh-pages estar pronto. Alguns documentos estavam em comentario nas issues para nao perder a rastreabilidade

**Comment by caue96** [comment]
Oi @EsioFreitas nós fizemos algumas alterações em alguns dos documentos que você apontou e gostariamos de saber se você ainda tem considerações a fazer em algum deles e quais seriam as considerações para que possamos melhorá-los.

**Comment by EsioFreitas** [comment]
Ola! Os documentos ficaram bem melhores!! Gostei! Em aspectos gerais, estao legais! Agora vamos para a proxima fase! hehe
