### ISSUE TITLE
Elaborar estimativas de custos e esforços p/ projeto

### ISSUE THREAD

**Issue by jppgomes** [UnBArqDsw/2020.1_G10_QRodizio#17]
Elaborar estimativas de custos e esforços para o projeto.

- Estimativa de custos - [ ] 

- Estimativas de esforços - [ ]

**Comment by fabio1079** [comment]
No [Termo de abertura do projeto](https://unbarqdsw.github.io/2020.1_G10_QRodizio/termo_de_abertura.html) tem os custos do projeto.

**Comment by lucasmidlhey** [comment]
As estimativas e custos estão dentro do TAP
