### ISSUE TITLE
Aplicar metodologia Design Sprint

### ISSUE THREAD

**Issue by jppgomes** [UnBArqDsw/2020.1_G10_QRodizio#18]
O Design Sprint é uma metodologia desenvolvida pelo Google Ventures para atacar esse problema. É uma maneira ágil, estruturada e colaborativa de conceituar e trancrever uma ideia em um curto espaço de tempo.

**Comment by caue96** [comment]
Fizemos o último dia de nosso design sprint hoje pela manhã.
