### ISSUE TITLE
Criar diagrama de componentes

### ISSUE THREAD

**Issue by lucasmidlhey** [UnBArqDsw/2020.1_G10_QRodizio#27]
Diagrama de componentes da UML ilustra como as classes deverão se encontrar organizadas através da noção de componentes de trabalho. Por exemplo, pode-se explicitar, para cada componente, qual das classes que ele representa. É utilizado para: Modelar os dados do código fonte, do código executável do software.

**Comment by jppgomes** [comment]
finalizado
