### ISSUE TITLE
Gerar QR Code

### ISSUE THREAD

**Issue by fabio1079** [UnBArqDsw/2020.1_G10_QRodizio#41]
Gerar QR Code no backend.
Não precisa de integração com frontend por enquanto, basta criar um mecanismo que gere QR Codes no backend.

- [x] gerar QR Code
- [x] testes*

**PS**:
* Tente testar, mas por enquanto considere como um extra.

**Comment by jppgomes** [comment]
Olhar biblioteca : https://github.com/lincolnloop/python-qrcode

**Comment by jppgomes** [comment]
Instalação : https://pypi.org/project/Flask-QRcode/
