### ISSUE TITLE
Criar perfil de gerente

### ISSUE THREAD

**Issue by lucasmidlhey** [UnBArqDsw/2020.1_G10_QRodizio#52]
o sistema deve ter um perfil especifico de gerente que pode controlar funcionários.

- [x] Cadastrar outro gerente

- [x] cadastrar funcionarios

- [x] remover funcionarios

- [x] alterar perfil de funcionario

**Comment by fabio1079** [comment]
* Backend merge https://github.com/UnBArqDsw/2020.1_G10_QRodizio_Backend/pull/9
* Frontend merge https://github.com/UnBArqDsw/2020.1_G10_QRodizio_Frontend/pull/8
