### ISSUE TITLE
Criar documento de plano de riscos

### ISSUE THREAD

**Issue by lucasmidlhey** [UnBArqDsw/2020.1_G10_QRodizio#7]
Definir como serão as medidas para lidar, monitorar e planejar as possíveis ameaças ou oportunidades durante o andamento do projeto.

Este documento deve conter: 

- [x] Metodologia

<s>- [ ] Papéis e responsabilidades</s>

- [x] Categorias de riscos

- [x] Probabilidade e impacto

**Comment by jppgomes** [comment]
Falta passar para markdown e adicionar mais alguns riscos.
