### ISSUE TITLE
Criar Termo de abertura do projeto (TAP)

### ISSUE THREAD

**Issue by lucasmidlhey** [UnBArqDsw/2020.1_G10_QRodizio#8]
Este documento formaliza o início do projeto com aprovação dos stakeholders.

Este documento deve conter:

- [x] Definição de escopo

- [x] Cronograma

- [x] custos e eforços

- [x] definição de equipe

**Comment by jppgomes** [comment]
Falta definir cronograma

**Comment by caue96** [comment]
Documento finalizado
